### ISSUE TITLE
[running error] AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by cavaniho** [alexv0iceh/AutoChar#11]
`Traceback (most recent call last):
      File "E:\sd ui\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "E:\sd ui\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "E:\sd ui\stable-diffusion-webui\modules\txt2img.py", line 59, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "E:\sd ui\stable-diffusion-webui\modules\scripts.py", line 501, in run
        processed = script.run(p, *script_args)
      File "E:\sd ui\stable-diffusion-webui\scripts\AutoChar_v09.py", line 650, in run
        last_image_batch = sd_upscale(hr_fix_output, scale_factor, is_last,overlap, ui_upscaler_2)
      File "E:\sd ui\stable-diffusion-webui\scripts\AutoChar_v09.py", line 527, in sd_upscale
        sd_upscale_output = sd_up_run.run(self, instance_sd_upscale, None , overlap_func, ui_upscaler_2_func, sd_upscale_scale_factor)
      File "E:\sd ui\stable-diffusion-webui\scripts\sd_upscale.py", line 79, in run
        processed = processing.process_images(p)
      File "E:\sd ui\stable-diffusion-webui\modules\processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "E:\sd ui\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\sd ui\stable-diffusion-webui\modules\processing.py", line 734, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "E:\sd ui\stable-diffusion-webui\modules\processing.py", line 1250, in init
        self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
      File "E:\sd ui\stable-diffusion-webui\extensions\sd-webui-neutral-prompt\lib_neutral_prompt\cfg_denoiser_hijack.py", line 254, in create_sampler_hijack
        if name.startswith(('DDIM', 'PLMS', 'UniPC')):
    AttributeError: 'NoneType' object has no attribute 'startswith'`

**Comment by Zedvia** [comment]
Could you please give us more information? Settings. Reproduction steps if possible.

Also could you please try running it without the Neutral Prompt extension? We can't guarantee compatibility with all extensions. And I personally don't even know that extension and don't know what it does.

**Comment by cavaniho** [comment]
> Could you please give us more information? Settings. Reproduction steps if possible.
> 
> Also could you please try running it without the Neutral Prompt extension? We can't guarantee compatibility with all extensions. And I personally don't even know that extension and don't know what it does.

It should not be compatible with the neutral prompt extension. After I shut it down, I got an error: OpenCV (4.8.0) Layer with the requested id = 1 not found in the function 'CV: : within DNN: : dnn4_v20230620: : Net: : Impl: : getLayerData'

after i solve this, it can be run.
