### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by x-ili-x** [alexv0iceh/AutoChar#4]
venv "E:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
*** Error loading script: AutoChar_v08_release.py
    Traceback (most recent call last):
      File "E:\ai\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\ai\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1017, in get_code
      File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\ai\stable-diffusion-webui\scripts\AutoChar_v08_release.py", line 7
        <!DOCTYPE html>
        ^
    SyntaxError: invalid syntax

**Comment by x-ili-x** [comment]
ffs nevermind i didn't DL the raw file
